<?php
$lang['login_to_your_account']='Login to your Account';
$lang['username']="Username";
$lang['login']='Login';
$lang['parking']='Parking';
$lang['dashboard']='Dashboard';
$lang['user_details']='User Details';
$lang['allocation']='Allocation';
$lang['queue']='Queue';
$lang['users']='Users';

$lang['reports']='Reports';
$lang['change_password']='Change password';
$lang['logout']='Logout';
$lang['more_info']='More Info';
$lang['queue_members']='Queue Members';
$lang['queue']='Queue';
$lang['available']='Available';
$lang['allocated']='Allocated';
$lang['user_details']='User Details';
$lang['add_user']='Add User';
$lang['add']='Add';
$lang['show_entries']='Show entries';
$lang['search']='Search';
$lang['showing_entries']='Showing 1 to 10 of 166 entries';
$lang['previous']='Previous';
$lang['next']='Next';
$lang['copyright']='Copyright © '.date('Y').' Parking  ';
$lang['reserved']='All rights reserved.';

$lang['first_name']='First Name';
$lang['last_name']='Last Name';
$lang['apartment_no']='Apartment No';
$lang['email']='Email';
$lang['personal_number']='Personal Number';
$lang['post_no']='Post No';
$lang['post_ort']='Post Ort';
$lang['mobile']='Mobile';
$lang['address']='Address';
$lang['action']='Action';
$lang['submit']='Submit';
$lang['update']='Update';
$lang['back']='Back';
$lang['parking_type']='Parking Type';
$lang['amount_annual']='Amount(Annual)';
$lang['status']='Status';
$lang['active']='Active';
$lang['add_parking']='Add Parking';

$lang['inactive']='Inactive';
$lang['user']='User';
$lang['from_date']='From Date';
$lang['to_date']='To Date';
$lang['parking_allocation']='Parking Allocation ';
$lang['cancel']='Cancel';
$lang['confirm']='Confirm';
$lang['waiting']='Waiting';
$lang['close']='Close';
$lang['closed']='Closed';
$lang['queue_no']='Queue No ';
$lang['waiting_queue']='Waiting in the Queue';
$lang['parking_allocated']='Parking Allocated';
$lang['confirmed']='Confirmed';
$lang['waiting_decision']='Waiting for decision';
$lang['decline']='Decline';
$lang['generated_by']='Generated By';
$lang['report_by_month']='Report by Month';
$lang['view_pdf']='View PDF';
$lang['password']='Password';
$lang['update_password']='Update Password';
$lang['old_password']='Old Password';
$lang['new_password']='New Password';
$lang['confirm_password']='Confirm Password';
$lang['update_user_details']='Update User Details';
$lang['profile_details']='Profile Details';
$lang['parking_status']='Parking Status';
$lang['your_queue_no']='Your Queue No';
$lang['from_date']='From Date';
$lang['status']='Status';
$lang['alloted_parking']='Alloted Parking';
$lang['parking_starts_from']='Parking Starts from';

$lang['queue_starts_from']='Queue Starts from';
$lang['status_messages']='Status Messages:';
$lang['updated_admin_success']='Updated Admin Successfully';
$lang['user_add_success']='User Details has been added Successfully';
$lang['user_update_success']='User Details has been Updated Successfully';
$lang['park_add_success']='Added Parking Successfully';
$lang['park_update_success']='Updated Parking Successfully';
$lang['delete_success']='Your data deleted Successfully..';
$lang['parking_status']='Parking Status';//	Parkeringsstatus
$lang['batch_process']='Batch Process';//	Parkeringsstatus

$lang['edit']='Edit';
$lang['delete']='Delete';

//Parking Type
$lang['mcplats']='MC -Plats';
$lang['garage']='Garage';
$lang['carport']='Carport';
$lang['pplats']='P-plats';

$lang['parking_type']='Parking Type';
$lang['s_no']='S. No';
$lang['total']='Total';
$lang['top']='Top';
$lang['alloted_parking']='Alloted Parking';
$lang['back']='Back';
$lang['parking_name']='Parking Name';
$lang['select_parking']='Select Parking';
$lang['select_user']='Select User';
$lang['select']='Select';
$lang['allocation_add_success']='Added Allocation Successfully';
$lang['allocation_update_success']='Update Allocation Successfully';
$lang['allocation_delete_success']='Deleted Allocation Successfully';
$lang['generate_month_report']='Generate Month Report';
$lang['generate_month_success']='Generated  '.date('F').'Month Invoice Successfully..';

$lang['please_enter_old_password']='Please Enter Old Password"';
$lang['please_enter_valid_password']='Please Enter Valid Password';
$lang['please_enter_new_password']='Please Enter New Password';
$lang['please_enter_re_type_password']="Please Enter Re-Type Password";
$lang['please_enter_confirm_password']="Please Enter Confirm Password";

$lang['click_queue']='Please Click here to Place in the Queue';
$lang['start_queue']="Start Queue";
$lang['start_from_queue']="Do you want start queue?";
$lang['quit_queue']="Quit Queue";
$lang['end_date_confirmed']="End Date Confirmed";
$lang['you_are_not_parking']='You are not Parking';
$lang['status_bar']='Status Bar';
$lang['are_you_sure_quit_queue']='Are you sure? want to Quit Queue?';
$lang['yes']='Yes';
$lang['no']='No';
$lang['quit_from_queue']='You have Quit from Queue Successfully';
$lang['status_update']='Status has been updated Successfully';
$lang['profile']='Profile';
$lang['sign_out']='Sign Out';

$lang['cancel_parking_msg']='Are you sure want to cancel Parking';
$lang['delete_parking_msg']='Are you sure want to delete Parking';
$lang['from']='From';
$lang['cancel_parking']='Cancel Parking';
$lang['decline_allocation_msg']='Do you want to decline this Allocation?';
$lang['parking_change']='Which Parking user wants to change?';
$lang['allocation_decline_success']='Your Allocation Declined';
$lang['parking_cancel_admin']='Your Parking cancel request has been updated';
$lang['cancel_parking_next_month']='Parking will be cancelled from End of Next Month';
$lang['delete_message']='Your data deleted Successfully..';

$lang['no_user_delete']='Parking is already allocated to this User - Can not be deleted';

$lang['user_delete']='User can not be deleted, Kindly cancel the Allocated Parkings';
$lang['parking_delete']='Parking can not be deleted, Kindly cancel the Allocated Parkings';


//Profile
$lang['profile_updated']='Profile Updated Successfuddlly';
$lang['user_delete']='Are you sure want to delete?';
$lang['parking_amount']='Parking Amount';



//Mail
$lang['dear']='Dear';
$lang['your_allocation']='You have been placed in the Allocation of Parking';
$lang['queue_details_parking']='Queue Details - Parking';

$lang['your_parking_confirmed']='Your Parking has Confirmed';
$lang['confirmed_parking_subject']='Confirmed - Parking';

$lang['your_parking_not_alloted']='Your Parking is not Allocated';
$lang['parking_not_alloted_subject']='Parking - Not Allocated';

$lang['parking_closed']="Parking Closed";
$lang['your_parking']="Your Parking";
$lang['parking_confirmed']="Parking Confirmed";


$lang['your_parking_will_cancel']='Your Parking will be cancelled from';
$lang['cancel_request_parking']='Cancel - Your request Parking';

$lang['login_here']='Login  here';
$lang['login_details']='Login Details - Parking';

$lang['you_start_queue']='You have been placed in the queue from';

$lang['click_here_to']='Please Click here to ';
$lang['password_update']='Successfully Updated Password details';

$lang['thank_you_for_confirmation']='Thanks for your confirmation we ll get back to you after Parking Confirmed';




$lang['queue_cance_msg']='You are canceled from queue on';
$lang['queue_cancel_parking']='Queue Cancel - Parking';
$lang['cancel_from_parking']='Your Parking will cancel from queue on';
$lang['cancel_parking_subject']='Cancel - Parking';
$lang['your_parking_will_be_cancel_from']='Your Parking will be cancelled from';
$lang['allocation_confirmed_message']='Your Allocation request has been Confirmed';
$lang['parking_change_confirm']="Parking Change Confirmation";


$lang['change_parking']='Please Select which Parking do you want Change?';

//version 1.1

$lang['parking_group']='Parking Group';
$lang['select_parking_group']='Select Group';
$lang['required']='This field is required.';
$lang["enter_parking_amount"]='Please Enter Parking Amount';
$lang['enter_valid_amount']="Please Enter valid Amount";
$lang['parking_already_added']='Parking already Added';

$lang['type']='Type';
$lang['name']='Name';
$lang['group']='Group';

$lang['has_been_confirmed_you']='has been confirmed you.';
$lang['kindly_contact_before']='Kindly contact Admin for Contract before ';
$lang['has_been_confirmed_to']="has been confirmed to";
$lang['kindly_contract_approve']='Kindly write a contract and approve this Allocation.';
$lang['admin']='Admin';
$lang['approve']='Approve';
$lang['contract_no']='Contract No';

$lang['on']='on';

$lang['contract_sign']='Congrats, Contract has been signed for';
$lang['parking_start_from']='You will start using the parking from';
$lang['billing_details']='Kindly include the details in the billing.';
$lang['biiling_confirm_subject']='New parking allocated, Please find the details below';
$lang['biiling_decline_subject']='Parking Canceled.';
$lang['billing_cancel']='This Parking has been cancelled';


$lang['start_from']="Start From";
$lang['approve_confirm_messge']="Parking has been confirmed successfully";
$lang['approve_cancel_messge']="Parking has been declined";
$lang['do_you_want_approve']="Do you want approved this Parking?";

$lang['decline_parking_msg']='Do you want to decline this Parking?';
$lang['confirm_parking_cancel']='Your confirm parking cancelled';
$lang['parking_decline']='Admin has declined the allocated parking <parking_no>. Kindly contact Admin for futher information.';
$lang['no_records_available']='No Records Available';

$lang['invalid_credentials']='Ogiltigt användarnamn och lösenord';


?>